COMMON_PORTS = {
    20: "FTP-DATA",
    21: "FTP",
    22: "SSH",
    23: "Telnet",
    25: "SMTP",
    53: "DNS",
    67: "DHCP",
    69: "TFTP",
    80: "HTTP",
    110: "POP3",
    111: "RPCbind",
    123: "NTP",
    135: "MSRPC",
    139: "NetBIOS-SSN",
    143: "IMAP",
    161: "SNMP",
    389: "LDAP",
    443: "HTTPS",
    445: "SMB",
    465: "SMTPS",
    514: "Syslog",
    587: "SMTP (submission)",
    636: "LDAPS",
    993: "IMAPS",
    995: "POP3S",
    1433: "MSSQL",
    1521: "Oracle DB",
    2049: "NFS",
    2375: "Docker API",
    3000: "Dev server (common: Node/Grafana)",
    3306: "MySQL",
    3389: "RDP",
    5000: "Dev server (common: Flask)",
    5432: "PostgreSQL",
    5900: "VNC",
    5984: "CouchDB",
    6379: "Redis",
    8080: "HTTP-Alt / Proxy",
    8443: "HTTPS-Alt",
    9200: "Elasticsearch",
    27017: "MongoDB",
}

VULN_SUGGESTIONS = {
    20: ["Passive/active FTP data channel; often tied to the same risks as port 21."],
    21: ["FTP may allow anonymous login if misconfigured.", "Credentials are usually transmitted in plain text."],
    22: ["Common target for brute-force attacks if exposed to the internet.", "Check the OpenSSH version in the banner against known CVEs."],
    23: ["Telnet transmits everything in plain text (no encryption).", "Considered obsolete/insecure for production use."],
    25: ["Server may be misconfigured as an open relay.", "May allow user enumeration via VRFY/EXPN commands."],
    53: ["Misconfiguration may allow zone transfer (AXFR) to any host.", "Can be abused in DNS amplification attacks."],
    69: ["TFTP has no authentication by design; often exposes configuration files."],
    80: ["Check for missing security headers (CSP, X-Frame-Options, etc).", "Outdated CMS/frameworks often have public CVEs.", "Check for exposed admin panels or default credentials."],
    110: ["POP3 without TLS transmits credentials in plain text."],
    139: ["NetBIOS can leak host information (name, domain, users) via enumeration."],
    143: ["IMAP without TLS transmits credentials in plain text."],
    161: ["SNMP with default community strings (e.g. 'public') can leak device info."],
    389: ["LDAP without TLS transmits data in plain text.", "Anonymous bind may be allowed if misconfigured."],
    443: ["Check TLS configuration (old versions, weak ciphers, expired certificate)."],
    445: ["SMB is historically associated with critical remote code execution exploits.", "May allow null sessions or overly permissive shares."],
    465: ["Check TLS/SSL configuration for outdated protocol versions."],
    514: ["Syslog is often unauthenticated and unencrypted by default."],
    636: ["Check LDAPS certificate validity and TLS configuration."],
    1433: ["Default 'sa' account with a weak password is a common misconfiguration."],
    1521: ["Default accounts and weak listener configuration are common issues."],
    2049: ["NFS exports with overly permissive access are a common misconfiguration."],
    2375: ["Docker API exposed without authentication can lead to full host compromise."],
    3306: ["Instances exposed to the internet with weak/root credentials are a classic risk."],
    3389: ["Exposed RDP is a constant target for brute-force attacks.", "Check patch level against known critical RDP CVEs."],
    5432: ["Weak authentication or misconfigured 'trust' auth may allow passwordless access."],
    5900: ["VNC often runs without authentication or with a weak default password."],
    5984: ["Older CouchDB versions had unauthenticated admin access by default."],
    6379: ["Redis has no authentication by default; an exposed instance can be read/written freely."],
    8080: ["Often used for admin panels or proxies; check for default credentials."],
    9200: ["Elasticsearch without authentication exposed to the internet is a common cause of data leaks."],
    27017: ["MongoDB without authentication enabled is a classic cause of mass data leaks."],
}

def get_service_name(port):
    return COMMON_PORTS.get(port, "Unknown Service")

def get_vuln_suggestions(port):
    return VULN_SUGGESTIONS.get(port, ["No specific vulnerabilities found for this port."])